id = "lispbm"
name = "lispBM"
version = "0.0.1"
schema_version = 1
authors = [
    "Joakim Lundborg <joakim.lundborg@gmail.com>",
    "Rasmus Söderhielm <rasmus.soderhielm@gmail.com>",
]
description = "lispBM"
repository = "https://github.com/cortex/zed-lispbm"

[grammars.lispbm]
repository = "file:///home/rasmus/projects/misc/tree-sitter-lispbm"
rev = "feat/directives"
